# Generated by Django 4.0.8 on 2024-05-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('keywords', models.CharField(max_length=255)),
                ('robots', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'seo',
                'verbose_name_plural': 'seo',
            },
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
