# Generated by Django 4.0.8 on 2024-05-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_seo_alter_slider_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='OG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('type', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='og')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
