# Generated by Django 4.0.8 on 2024-06-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_og'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='og',
            options={'verbose_name': 'Open Graph', 'verbose_name_plural': 'Open Graphs'},
        ),
    ]
