# Generated by Django 4.0.8 on 2024-06-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_hometext_lang_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometext',
            old_name='lang_code',
            new_name='en_lang_code',
        ),
        migrations.AddField(
            model_name='hometext',
            name='hy_lang_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='hometext',
            name='ru_lang_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
