# Generated by Django 4.0.8 on 2024-06-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_rename_lang_code_hometext_en_lang_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeText',
        ),
    ]
